application: e-maxx-eng
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /test.php
  script: test.php

- url: /(.+\.html)$
  script: serve.php

- url: /
  script: serve.php
